name: Go Build

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      build-file:
        required: true
        type: string
      output-file:
        required: true
        type: string
jobs:
  build:
    
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v && ls

    - name: Test
      run: go test -v ./...

    - name: Tarball File
      run: tar cfz ${{ inputs.output-file }} .diary.yaml.example ${{ inputs.build-file }}
    
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ inputs.output-file }}
