name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    uses: ./.github/workflows/go-build
    with:
      os: ubuntu-latest
      build-file: diary
      output-file: diary-linux_x64.tar.gz
      
  build-macOS:
    uses: ./.github/workflows/go-build
    with:
      os: macOS-latest
      build-file: diary
      output-file: diary-darwin_x64.tar.gz
      
  build-windows:
    uses: ./.github/workflows/go-build
    with:
      os: windows-latest
      build-file: diary.exe
      output-file: diary-win64.tar.gz
