name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    uses: ./.github/workflows/go-build.yml
    with:
      os: ubuntu-latest
      build-file: diary
      output-file: diary-linux_x64
      
  build-macOS:
    uses: ./.github/workflows/go-build.yml
    with:
      os: macOS-latest
      build-file: diary
      output-file: diary-darwin_x64
      
  build-windows:
    uses: ./.github/workflows/go-build.yml
    with:
      os: windows-latest
      build-file: diary.exe
      output-file: diary-win64
